control: {
  parameters: {Kd: 0.0, Ki: 558.5, Kp: 73.2},
  power: {max: 1500, min: 500},
  step: {power: 800, trigger: 2},
  manual: {power: 1000},
  automatic: {width: 2.3, reg: 40,  time: 60, track_number: 0}
}
