control: {
  parameters: {Kd: 0.0, Ki: 558.5, Kp: 73.2},
  power: {max: 1500, min: 0},
  step: {power: 800, trigger: 2},
  manual: {power: 1000},
  automatic: {width: 3.4},
  ramp: {initial: 600, final: 1500, step: 100, t_time: 12.5}
}
